### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Nikratio** [g2p/bedup#25]
Hi,

This (probably) isn't really a bug report, but I couldn't find any other appropriate discussion forum.

I've just discovered bedup and it looks like a great tool. However, I'm at a complete loss understanding what the program is spending its time on. At the moment, I'm seeing the following output:

```
# ~nikratio/.local/bin/bedup dedup /media/backup/ 
Scanning volume /media/backup/ generations from 0 to 390, with size cutoff 8388608
00.00 Scanned 63 retained 1
Scanning volume /media/backup/2013-03-10_12:56 generations from 0 to 441, with size cutoff 8388608
01:36.0 Scanned 2731281 retained 406
Scanning volume /media/backup/2013-08-03_11:02 generations from 0 to 437, with size cutoff 8388608
02:00.5 Scanned 3491040 retained 1926
Scanning volume /media/backup/2013-03-10_13:35 generations from 0 to 442, with size cutoff 8388608
26.22 Scanned 3427435 retained 1899
Scanning volume /media/backup/2013-04-02_20:25 generations from 0 to 390, with size cutoff 8388608
37.77 Scanned 3751994 retained 2047
Deduplicating filesystem <backup>
29:09.9 Size group 1/1854 sampled 3 hashed 2 freed 0
```

This has been unchanged for about 25 minutes, so I'm wondering what bedup is actually spending its time own (there seems to be lots of harddisk activity).

I was assuming that btrfs already stores checksums for all data blocks, so that when the scanning is complete bedup could already tell me exactly how much duplicated blocks were found, and how much space will be freed.  Furthermore, I sort of assumed that the deduplication itself would be quick, since only the metadata has to be updated to refer to the deduplicated data blocks.

However, it seems I'm wrong on all counts. It seems there is a lot of work that needs to be done after scanning, and I have no idea what "sampled" and "hashed" may mean.

It would be great if the README could briefly explain the program output, and maybe give a rough outline of the steps that need to be done (and how time intensive they are).

Thanks a lot for providing this nice tool!

**Comment by g2p** [comment]
Closing, there isn't anything I wish to change here (though I'd like to be able to switch to the dedup syscall). I've opened the wiki if it helps.

**Comment by unhammer** [comment]
could someone who knows this stuff verify my assumptions? https://github.com/g2p/bedup/wiki/Understanding-the-tracking-output
