### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by weirdtalk** [g2p/bedup#29]
On Ubuntu 13.10 with 1 week old btrfs raid10 w/ lzo compression on 4x2TB w/ ~2TB data and ~10 snapshots. Was curious to see what the saving of deduplication would be so cloned master and I ran:

sudo ./dedup /data

for about 24hrs and reclaimed ~80GB before getting this error (omitting duplicate lines, sorry don't have the top of the trace):

  File "~/.local/lib/python2.7/site-packages/contextlib2.py", line 244, in _invoke_next_callback
    suppress_exc = _invoke_next_callback(exc_details)
  File "~/.local/lib/python2.7/site-packages/contextlib2.py", line 244, in _invoke_next_callback
    suppress_exc = _invoke_next_callback(exc_details)
  File "~/.local/lib/python2.7/site-packages/contextlib2.py", line 246, in _invoke_next_callback
    suppress_exc = cb(*sys.exc_info())
  File "~/.local/lib/python2.7/site-packages/contextlib2.py", line 171, in _exit_wrapper
    return cm_exit(cm, *exc_details)
RuntimeError: maximum recursion depth exceeded

My curiosity is satiated for now, but let me know if you could use any more details or would like me to try and reproduce the error again.

**Comment by sulaweyo** [comment]
Jep same her on deduplicating some SVN workspaces :(

**Comment by lpirl** [comment]
+1

**Comment by mac-linux-free** [comment]
same to me .... max recursion depth exeeded ... on debian and ubuntu 14.04 .... what could we do ?

**Comment by lpirl** [comment]
I contacted the developer of ``contextlib2``. He is aware of the problem, there is a fix but he haven't found the time to pack a new release so far.

**Comment by mgorny** [comment]
Do you mean https://bitbucket.org/ncoghlan/contextlib2/commits/170d5144455767dc39065f804d18df2104df1b0c? Sadly, that seems to be only possibly relevant commit after the last release, and it's around 1.5yr since it was committed. `contextlib2` seems pretty much dead to me.

**Comment by mac-linux-free** [comment]
so bedup development is dead? where is the light at the end...?

**Comment by sulaweyo** [comment]
I switched over to duperemove. It's not perfect on larger sets but you can run it on folders so i just do smaller chunks. At least i never had immutable files left over or OOM issues as i had with bedup again and again.

**Comment by mac-linux-free** [comment]
good, that is what I do now. hope it work for my 80tb store.

**Comment by sulaweyo** [comment]
I am deduplicating source code branches so i use a blocksize of 8K while duperemove usually usees 128K. For really large storage increase that maybe. With 8K even my 200GB deduped to 20GB generate way above 2GB of hashes and duperemove uses memory accordingly.

**Comment by mac-linux-free** [comment]
where are the hashes stored? only in memory? if the hashes are generated one time are they used again with delta support? i checked out duperemove and it is version 0.10-dev...i think i remember some oom´s with duperemove 0.08 on my 80tb store

**Comment by sulaweyo** [comment]
I did not check the code but it looks like the hashes are stored in memory. You can write them to a file but still they will be loaded to memory again as a whole. At least that is what it looks like. From the issues there it looks like they want to move that to sqllite which could help to drop the memory consumption a lot i guess. Guess it's better to directly ask there.

**Comment by mac-linux-free** [comment]
ok i tested now ... my 80tb store consumed 128gb ram with duperemove read only ... my server has 256gb ram so no problem for me :) the really great thing about duperemove is the multithreaded hashing so with 24cores and 256gb ram it works.

**Comment by g2p** [comment]
bedup is now Python3-only (way overdue), and doesn't use contextlib2 anymore.
