### ISSUE TITLE
Does it work…?

### ISSUE THREAD

**Issue by grinapo** [g2p/bedup#44]
Uh I hate it because I find it unlikely but... I tried to see what dedup does and it did nothing.

- Linux 3.13-1-amd64 #1 SMP Debian 3.13.4-1 (2014-02-22) x86_64 GNU/Linux
* I have a 100GB btrfs fs with 80GB+ files.
* btrfs fi df /mnt/btrfs
* cd tmp/ ; for i in {1..5}; do cp -av ../misc/stuff dupe${i}; done
* btrfs fi df /mnt/btrfs
* bedup dedup
* btrfs fi df /mnt/btrfs

The stuff is around 1GB, and in step 4 it's correctly allocated:
Data, single: total=94.00GiB, used=93.55GiB
System, DUP: total=8.00MiB, used=20.00KiB
System, single: total=4.00MiB, used=0.00
Metadata, DUP: total=1.38GiB, used=205.36MiB

The problem is that:
1) dedup lists 8-10 files as "deduplicating", there should've been 500+
2) in step6 the status is exactly the same, give or take a few hundred MBs

There should've been 4GB free'd. Or?

**Comment by ivanbaldo** [comment]
This report should be closed, thanks.

**Comment by g2p** [comment]
Indeed. Closed, works for me.
