### ISSUE TITLE
bedup shows retained files in newely created read-only snapshot

### ISSUE THREAD

**Issue by Shished** [g2p/bedup#54]
`# btrfs su sn -r /home /home/snapshot`
`# btrfs fi sync /home`
`# bedup scan /home`
...................................
`Scanning volume /home/snapshot generations from 0 to 25603, with size cutoff 8388608
03:07.1 Scanned 8293716 retained 8579`

btrfs fi usage /home doesn't shows changes in used and free space after creation of the snapshot.

I'm using bedup 0.9.0, btrfsprogs 3.16.2, linux 3.17.1, OS: openSUSE 13.1 x86_64.

**Comment by g2p** [comment]
Those are new inodes.  The (ino, dev) pair has changed and there's no way to detect that they match an existing inode before the second stage of deduplication (which looks at extents).
